import hashlib
import json
import subprocess
import sys
import unittest
from pathlib import Path

from tests.fixtures import (cart_png, cart_rom, gba_rom, legacy_code,
                            png_from_raw, temporary_directory)

ROOT = Path(__file__).resolve().parents[1]
PICO_SCRIPTS = ("pico8_cart.py", "analyze_cart.py", "create_analysis_case.py")
GBA_SCRIPTS = ("gba_rom.py", "gba_analyze.py")
CASE_FLAGS = ("--title", "Synthetic", "--author", "Test suite",
              "--source-url", "https://example.invalid/synthetic",
              "--license", "Original synthetic test data",
              "--permission-basis", "Generated by this test suite")


class CliTests(unittest.TestCase):
    def setUp(self):
        self.directory = temporary_directory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)

    def run_cli(self, script, *args):
        return subprocess.run([sys.executable, "-X", "utf8", str(ROOT / "scripts" / script),
                               *(str(arg) for arg in args)], cwd=self.root,
                              capture_output=True, text=True, encoding="utf-8", timeout=20)

    def assert_error(self, result, message=None):
        self.assertEqual(result.returncode, 2, result.stderr)
        self.assertEqual(result.stdout, "")
        self.assertTrue(result.stderr.startswith("error:"), result.stderr)
        self.assertNotIn("Traceback", result.stderr)
        if message:
            self.assertIn(message, result.stderr)

    def pico_args(self, script, source, *extra):
        if script == "create_analysis_case.py":
            return (source, self.root / "case", *CASE_FLAGS, *extra)
        return (source, *extra)

    def test_every_pico_cli_handles_malformed_binary_without_traceback(self):
        image, _ = cart_png()
        cases = [("truncated.p8.png", image[:25]),
                 ("crc.p8.png", image[:-1] + bytes([image[-1] ^ 1])),
                 ("zlib.p8.png", png_from_raw(160, 205, b"", compressed=b"invalid")),
                 ("legacy.p8.rom", cart_rom(legacy_code(b"\0A\x3c\0", 3))),
                 ("pxa.p8.rom", cart_rom(b"\0pxa\0\x01\xff\xff")),
                 ("short.p8.rom", bytes(10)), ("garbage.p8", b"garbage"),
                 ("utf8.p8", b"\xff"), ("signature.p8.png", b"bad png"),
                 ("version.p8", b"pico-8 cartridge\nversion \n__lua__")]
        for name, contents in cases:
            source = self.root / name
            source.write_bytes(contents)
            for script in PICO_SCRIPTS:
                with self.subTest(name=name, script=script):
                    self.assert_error(self.run_cli(script, *self.pico_args(script, source)))
                    self.assertFalse((self.root / "case").exists())

    def test_every_cli_handles_missing_input(self):
        for script in PICO_SCRIPTS + GBA_SCRIPTS:
            suffix = ".p8" if script in PICO_SCRIPTS else ".gba"
            source = self.root / ("missing" + suffix)
            with self.subTest(script=script):
                self.assert_error(self.run_cli(script, *self.pico_args(script, source)))

    def test_gba_clis_reject_short_and_unsupported_inputs(self):
        for name, contents in [("short.gba", bytes(0xBF)), ("wrong.txt", gba_rom())]:
            source = self.root / name
            source.write_bytes(contents)
            for script in GBA_SCRIPTS:
                with self.subTest(name=name, script=script):
                    self.assert_error(self.run_cli(script, source))

    def test_gba_cli_rejects_nonpositive_instruction_budget(self):
        source = self.root / "valid.gba"
        source.write_bytes(gba_rom())
        for budget in [0, -10]:
            with self.subTest(budget=budget):
                self.assert_error(self.run_cli("gba_analyze.py", source, "--max-instructions", budget),
                                  "positive")

    def test_odd_asset_hex_is_an_error_before_case_creation(self):
        for section in ["map", "gff"]:
            source = self.root / "odd.p8"
            source.write_text("pico-8 cartridge\n__lua__\nprint(1)\n__" + section + "__\nf\n",
                              encoding="utf-8")
            for script in ["analyze_cart.py", "create_analysis_case.py"]:
                with self.subTest(section=section, script=script):
                    self.assert_error(self.run_cli(script, *self.pico_args(script, source)))
                    self.assertFalse((self.root / "case").exists())

    def test_valid_png_summary_code_and_asset_extraction(self):
        source = self.root / "synthetic.p8.png"
        image, payload = cart_png()
        source.write_bytes(image)
        code = self.root / "code.lua"
        rom = self.root / "data.rom"
        output = self.root / "unpacked"
        result = self.run_cli("pico8_cart.py", source, "--json", "--extract-code", code,
                              "--extract-rom", rom, "--extract-dir", output)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        summary = json.loads(result.stdout)
        self.assertEqual(summary["format"], "p8.png")
        self.assertEqual(summary["trailer_bytes"], 32)
        self.assertEqual(code.read_text(encoding="utf-8"), "print(1)\n")
        self.assertEqual(rom.read_bytes(), payload[:0x4300])
        self.assertEqual((output / "trailer.bin").read_bytes(), payload[0x8000:])
        self.assert_error(self.run_cli("pico8_cart.py", source, "--extract-dir", output))

    def test_valid_analysis_json_and_markdown_outputs(self):
        source = self.root / "synthetic.p8"
        source.write_text("pico-8 cartridge\nversion 42\n__lua__\n"
                          "function _draw()\n cls()\n print('█')\nend\n", encoding="utf-8")
        result = self.run_cli("analyze_cart.py", source, "--format", "json")
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads(result.stdout)
        self.assertEqual(report["code"]["callbacks"], ["_draw"])
        self.assertEqual(report["code"]["api_calls"], {"cls": 1, "print": 1})
        output = self.root / "report.md"
        result = self.run_cli("analyze_cart.py", source, "--format", "markdown", "--output", output)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "")
        self.assertIn("Analyst completion required", output.read_text(encoding="utf-8"))

    def test_case_manifest_reports_and_explicit_copy(self):
        source = self.root / "synthetic.p8.rom"
        raw = cart_rom()
        source.write_bytes(raw)
        for copy in [False, True]:
            output = self.root / ("copy-case" if copy else "report-case")
            result = self.run_cli("create_analysis_case.py", source, output, *CASE_FLAGS,
                                  *(["--copy-cart"] if copy else []))
            with self.subTest(copy=copy):
                self.assertEqual(result.returncode, 0, result.stderr)
                manifest = json.loads((output / "rights.json").read_text(encoding="utf-8"))
                self.assertEqual(manifest["sha256"], hashlib.sha256(raw).hexdigest())
                self.assertEqual(manifest["cart_copied_into_case"], copy)
                report = json.loads((output / "static-analysis.json").read_text(encoding="utf-8"))
                self.assertEqual(report["rights"], manifest)
                self.assertTrue((output / "static-analysis.md").is_file())
                self.assertEqual((output / source.name).exists(), copy)
                if copy:
                    self.assertEqual((output / source.name).read_bytes(), raw)
                self.assert_error(self.run_cli("create_analysis_case.py", source, output, *CASE_FLAGS),
                                  "already exists")

    def test_valid_gba_json_and_file_outputs(self):
        source = self.root / "synthetic.gba"
        source.write_bytes(gba_rom())
        for script in GBA_SCRIPTS:
            output = self.root / (script + ".json")
            result = self.run_cli(script, source)
            with self.subTest(script=script):
                self.assertEqual(result.returncode, 0, result.stderr)
                report = json.loads(result.stdout)
                self.assertEqual(report["source"]["filename"], source.name)
                result = self.run_cli(script, source, "--output", output)
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stdout, "")
                self.assertEqual(json.loads(output.read_text(encoding="utf-8")), report)

    def test_unwritable_output_paths_fail_cleanly(self):
        pico_source = self.root / "valid.p8.rom"
        pico_source.write_bytes(cart_rom())
        gba_source = self.root / "valid.gba"
        gba_source.write_bytes(gba_rom())
        missing_parent = self.root / "missing-parent" / "output.json"
        for script in ["pico8_cart.py", "analyze_cart.py", *GBA_SCRIPTS]:
            source = pico_source if script in PICO_SCRIPTS else gba_source
            option = "--extract-code" if script == "pico8_cart.py" else "--output"
            with self.subTest(script=script):
                self.assert_error(self.run_cli(script, source, option, missing_parent))
        blocked = self.root / "blocked"
        blocked.write_text("file prevents directory creation", encoding="utf-8")
        self.assert_error(self.run_cli("create_analysis_case.py", pico_source, blocked / "case", *CASE_FLAGS))
